project:
  type: website
  output-dir: docs

website:
  title: "Accelerometry in R"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: tutorial.qmd
        text: Tutorial
  repo-url: https://github.com/jhuwit/accel_in_r
  image: images/WIT.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



