project:
  type: website
  output-dir: docs

website:
  title: "Accelerometry Analysis and Processing in R"
  navbar:
    left:
      - href: index.qmd
        text: Home/About
      - tutorial.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



