project:
  type: website
  output-dir: docs

website:
  title: "accel_in_r"
  navbar:
    left:
      - href: index.qmd
        text: Home/About
      - tutorial.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



